# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231995ba0c1b524c10507ce606d7ceec94910abd80ae5aef697a525fc39d9c580ef1b6b970c1940789db9ea71772af785ee27da447d814319c5c6bb11421f9b5

test:
  secret_key_base: d6d0ac3ead9d2561c79978fcee0777b5a236961cf15ab97717898c3e3ce8dc3ea7c0d2b4c39047b525e576733002b6641ec51abd8ff090b994e2b702f2cacc10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
